### ISSUE TITLE
Avalonia.Controls.ToolBar.Demo Build Failure

### ISSUE THREAD

**Issue by seoyhaein** [Tulesha/Avalonia.Controls.ToolBar#1]
Hello,

I've encountered a build issue with the Avalonia.Controls.ToolBar.Demo project and would like to seek assistance in resolving it. Below are the details of the issues I faced, along with the environment setup and steps I've taken to troubleshoot.

Issue Description
Initially, I received the following error when trying to build the project:

"Microsoft.PackageDependencyResolution.targets(266, 5): [NETSDK1004]"

I attempted a **dotnet restore**, which led to another error. It seems the issue might be related to MSBuild.

**Comment by Tulesha** [comment]
@seoyhaein I fix MSBuild issue, you can update main branch
